### ISSUE TITLE
IdentityModel.OidcClient.LoginAsync()[Android] does not launch browser.

### ISSUE THREAD

**Issue by KirylAkulich1** [IdentityModel/IdentityModel.OidcClient#337]
I've got issue with Android. If I call `IdentityModel.OidcClient.LoginAsync` and send application to background after that, using system buttons("Home" or "Overview") then I wait Task endlessly and google chrome is not launched.

**Comment by leastprivilege** [comment]
I am sorry - I only provide the base-library. Did you check the contributed samples?

**Comment by KirylAkulich1** [comment]
What do you mean under "contributed samples". I'm just using IdentityModel.OidcClient and can get any result when LoginAsync is called

**Comment by leastprivilege** [comment]
e.g. https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/main/AndroidClientChromeCustomTabs

**Comment by KirylAkulich1** [comment]
Sorry for question. There is problem with Browser
