### ISSUE TITLE
IdentityModel.OidcClient migration from 3.1.2 to 4.0 in UWP App

### ISSUE THREAD

**Issue by surensaluka** [IdentityModel/IdentityModel.OidcClient#343]
I have recently updated the nuget package of IdentityModel.OidcClient from version 3.1.2 to 4.0. Now I get errors on my existing implementation due to missing properties and couldn't figure how to migrate from XXX to 4.0.

` return new OidcClientOptions
                {
                    Authority = "https://qawebsvr.boardpac.local:450", //Case Sensitive!
                    ClientId = "boardpac.main.windows",
                    Scope = "openid profile email offline_access",
                    Flow = OidcClientOptions.AuthenticationFlow.AuthorizationCode,
                    RedirectUri = WebAuthenticationBroker.GetCurrentApplicationCallbackUri().AbsoluteUri,
                    ResponseMode = OidcClientOptions.AuthorizeResponseMode.Redirect,

                    Browser = new WabBrowser(enableWindowsAuthentication: false)
                };`

In the new v4 of the nuget, some properties of OidcClientOptions such as `Flow`, `AuthorizeResponseMode`, `AuthenticationFlow` are not recognized. Any help on migrating to v4 is very much appreciated.

**Comment by leastprivilege** [comment]
I removed hybrid flow - it will now always do code flow with redirect response mode.
