### ISSUE TITLE
IdToken validation nullreference

### ISSUE THREAD

**Issue by l-o-l** [IdentityModel/IdentityModel.OidcClient#346]
Was a pain to figure out what was wrong until I downloaded the source:

OidcClient.ProcessResponseAsync()...
                if (result.TokenResponse.IdentityToken != null)
                {
                    if (!string.Equals(userInfoSub.Value, result.User.FindFirst(JwtClaimTypes.Subject).Value))

If the User doesn't have the sub claim then crash. 

This happened because I was using System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken to create the ClaimsPrincipal inside IIdentityTokenValidator.ValidateAsync and the sub claim is not passed into it. 

I will look at another way of doing this.

**Comment by leastprivilege** [comment]
Hi, 

is there any actionable feedback?

There is a id token validation nuget already if you need that.
