### ISSUE TITLE
Question : authentication without browser

### ISSUE THREAD

**Issue by vd3d** [IdentityModel/IdentityModel.OidcClient#348]
Hi,

I have a Xamarin app, and I know that this library work well, but any "well know" mobile app can login/logout without opening or having an embedded browser.

So, I wish to know if it is possible to implement the authentication without a web browser?
First for email/password, then also for facebook login etc ?

PS: I currently use IdentityServer.

**Comment by leastprivilege** [comment]
"Native authentication" is an anti-pattern and not spec'd by OpenID Connect. That's why this library does not support it. All the "well-known" ones are doing it wrong ;)

see also:
https://datatracker.ietf.org/doc/html/rfc8252#section-4.1

**Comment by vd3d** [comment]
I understand, but it is not always a matter of "pure security" ;-)

It is sometime a mix of security risk / business value assessment. If the Business Value > Security Risk, then we should go native.

Here, it is a matter of user perception, and marketing.

You see ?

**Comment by leastprivilege** [comment]
This is totally fine. It is just not what this library is doing.
