### ISSUE TITLE
need unity client

### ISSUE THREAD

**Issue by yajiegithub** [IdentityModel/IdentityModel.OidcClient#354]
Which sample should be referred to?

**Comment by JoC0de** [comment]
It dopendes on witch platform your Unity app should run on. If you run on windows you can use the console sample https://github.com/IdentityModel/IdentityModel.OidcClient/blob/main/clients/ConsoleClient/Program.cs

**Comment by yajiegithub** [comment]
Thank you. The problem has been solved.
