### ISSUE TITLE
Getting unauthorized client issue

### ISSUE THREAD

**Issue by AjitKRuin** [IdentityModel/IdentityModel.OidcClient#355]
I updated identity model Odic client from 3.1 to 5.0 , I found response mode and flow missing from options , I commented them and deploy but getting Unauthorized client error.

**Comment by leastprivilege** [comment]
What IdP are you using?

**Comment by AjitKRuin** [comment]
I am using Xamarin android application , when I use identity model older version I was able to run application , now when I try to update identity model , as now I am trying to send my locale string in logout request state query string. But after I update I am getting unauthorized client error.

**Comment by AjitKRuin** [comment]
I tried to send cookies from Xamarin app to Oidc client , But I did not find any way to pass locale through cookies.

**Comment by AjitKRuin** [comment]
Any update @leastprivilege ?

**Comment by leastprivilege** [comment]
> What IdP are you using?

no - do you have one?

**Comment by kavitap0810** [comment]
@AjitKRuin  @leastprivilege  Is there any update on this issue? I am facing same in my Xamarin app.
