### ISSUE TITLE
How to pass Ui_Locale as a query string in Logout request model.

### ISSUE THREAD

**Issue by AjitKRuin** [IdentityModel/IdentityModel.OidcClient#356]
I am trying to pass query parameter for locale in logout request as like in login request but I was not able to pass.

**Comment by leastprivilege** [comment]
I guess this is not possible right now - this was not specified by OIDC. Is it now?

**Comment by AjitKRuin** [comment]
Is there any work around ? Like passing locale through cookies in logout request? From Xamarin to OIDC client

**Comment by leastprivilege** [comment]
No.
