### ISSUE TITLE
IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.RsaSecurityKey , KeyId: 

### ISSUE THREAD

**Issue by SrikJagz** [IdentityModel/IdentityModel.OidcClient#360]
Hi,

I'm facing this issue when connecting with AWS-Federate where RSA_2048 key size is being used. I have enabled the ShowPII to true so that this more detailed errorr is showing up. 

Currently I'm currently using IdentityModel.OidcClient version 2.5.1.0 and Microsoft.IdentityModel.Tokens.DLL version as 5.2.1.50208.

I have tried to upgrade to IdentityModel.OidcClient version 4.0 but so many public OidcOptions have been introduced and need to change the Interface to accomodate them.

Please let me know if there is a possibility to be able to accept the RSA_2048 KEYS with this version or else please suggest if there is a particular version where I can make work with minimum modifications.

**Comment by leastprivilege** [comment]
Hi 

I don't know. This version is very old. Feel free to fork and change the source code yourself.

**Comment by SrikJagz** [comment]
Hi, 

Can you please let me know the variable where I can Modify this RSA_Key if you have Idea.

Regards,
Srikanth

**Comment by leastprivilege** [comment]
No sorry.
