### ISSUE TITLE
.Net6 OidcClientOptions Browser main thread

### ISSUE THREAD

**Issue by AelyPro** [IdentityModel/IdentityModel.OidcClient#366]
Hello, my team is currently developping multiple software and we are using an unique loggin system for all of them. To do this we have an identity server and we are using OidcClient to let our user identify. We recently upgraded all our project to .Net6 and while it was painless for our WPF application, the login in our WinForms application don't seem to work anymore.

Here's my code to login with the OidcClient, the WinFormsWebView is the one in your sample.

```
OidcClient oidcClient = new OidcClient(new OidcClientOptions
{
    Authority = LicenceSystemConstant._BASE_URL_SERVER_AUTH_,
    ClientId = _LD_CLIENT_ID_,
    ClientSecret =_LD_CLIENT_SECRET_,
    Scope = "openid profile email offline_access ",
    RedirectUri = "https://not-used",
    Browser = new WinFormsWebView(),
    Policy = new Policy
    {
        RequireIdentityTokenSignature = false
    },
    LoadProfile = true,
    Resource =
    {
        serializedResource
    },
});

LoginResult loginResult = await oidcClient.LoginAsync();
```

Here is the exception (translated from french so might not be exact) :
Can't instantiate ActiveX control because the current thread isn't STA

We were originally using the same Browser for all our application (WPFBrowser) but I had the same STA problem so I tried the winform one from your sample without any luck.

From what I can see every calling thread is in STA until the _oidcClient.LoginAsync()_ call that invoke _InvokeAsync_ in the browser. But since I don't have access to the calling thread I can't change the thread appartment state.

Am I missing anything ?

**Comment by leastprivilege** [comment]
I don't know. This sample was contributed by someone. And I personally haven't touched WinForms for maybe 10 years or so ;)

**Comment by AelyPro** [comment]
After some more investigation the issue seem to be more global than that. We did some test on our WPF application and encounter a different problem that might be the cause of the crash in the winform application.

In the Browser used by the OidcClient we are declaring a Window to host the WebView2 that will be displaying the login page. Since the migration to .Net 6 the window creation return a System.InvalidOperationException (due to the fact that we are not in the main thread ?), we tried to wrap all the windows creation part into a call to the dispatch _Application.Current.Dispatcher?.Invoke_ without any luck (window appear but is white and we throw System.Runtime.InteropServices.COMException) .

Here is the current signinWindow creation :

```
Application.Current.Dispatcher?.Invoke(() =>
{
    var signinWindow = new Window()
    {
        Width = 1000,
        Height = 800,
        Title = "Identification",
        WindowStartupLocation = WindowStartupLocation.CenterScreen
    };
    signinWindow.Closing += (s, e) =>
    {
        semaphoreSlim.Release();
    };

     var webView = new WebView2();
     webView.NavigationStarting += (s, e) =>
    {
        if (IsBrowserNavigatingToRedirectUri(new Uri(e.Uri)))
        {
            e.Cancel = true;

           browserResult = new BrowserResult()
           {
               ResultType = BrowserResultType.Success,
               Response = new Uri(e.Uri).AbsoluteUri
           };

           semaphoreSlim.Release();
           signinWindow.Close();
        }
    };

    signinWindow.Content = webView;

    signinWindow.Show();
});
```

We are still investigating but in the meantime if anyone have a working sample in WPF .Net6 that would be realy helpfull !

**Comment by AelyPro** [comment]
As a last resort I downloaded the source code from the repo and linked directly to the OidcClient project instead of the package. For some obscures reasons everything is now working perfectly.

Here my nuggets versions : 
![Capture](https://user-images.githubusercontent.com/62246276/182818977-b01434ad-bb54-44cf-8cdb-5b507f7ad5b1.PNG)

**Comment by leastprivilege** [comment]
Oh - do not use v5.0.1 - I specifically unlisted that version since it had a bug from an external PR that would explain the behavior.

Try v5.0.0

<img width="892" alt="image" src="https://user-images.githubusercontent.com/1454075/182829252-62c41319-82f1-4ff9-a167-955f9e3545b5.png">

**Comment by AelyPro** [comment]
When retrograding to 5.0.0 everything seems to be working fine.
Thanks for your help !
