### ISSUE TITLE
Sticky sessions via cookies?

### ISSUE THREAD

**Issue by njlr** [IdentityModel/IdentityModel.OidcClient#369]
I am using `IdentityModel.OidcClient` to authenticate a local app against a Keycloak cluster. 

The cluster communicates grant codes, but there is some latency. This means that authentication can fail if the user starts the process on one instance in the cluster but completes against a different one. To mitigate this, I have enabled sticky-sessions using a cookie at the load balancer level. This works reliably in the web browser. 

The trouble comes when using this library for local apps in a particular way:

 1. Launch a local server the listens for a sign-on callback
 2. Generate a sign-in URL using `oidcClient.PrepareLoginAsync`
 3. Open the user's browser to the sign-in URL
 4. Wait for sign-on data on the local server
 5. Process the callback data using `oidcClient.ProcessResponseAsync`

Now, if step (2) and (5) happen quickly against two different instances then the grant code will be invalid and sign-in will fail. 

A work-around is to add a sleep (3 seconds seems sufficient) before step (5). 

But is there some way to pass cookies to `OidcClient` to enable sticky-sessions?

**Comment by leastprivilege** [comment]
this would be an implementation detail of your IBrowser implementation.
