### ISSUE TITLE
Using CryptoHelper as general-purpose helper for non-OIDC OAuth2 clients

### ISSUE THREAD

**Issue by hansmbakker** [IdentityModel/IdentityModel.OidcClient#372]
I would like to implement some OAuth2 flows with PKCE where the server does not have OIDC available (Spotify and Philips Hue).

The [`CryptoHelper` class](https://github.com/IdentityModel/IdentityModel.OidcClient/blob/e786a8715fbc853c0dfa88ded2404f1b1ebc1190/src/OidcClient/CryptoHelper.cs#L17) would be really helpful there, but it prevents people from using it outside the OidcClient - even though I think it should not have dependencies.

It is marked `internal` and has a dependency on `OidcClientOptions` but it seems that those `OidcClientOptions` do not really have a function in the class.

Would it make sense to make this class `public` and move it to the generic [`IdentityModel`](https://github.com/IdentityModel/IdentityModel) package? Or is there a better way to implement the OAuth2 flows for Spotify/Philips Hue?

Using OidcClient in general seems to have a dependency on the server implementing the `.well-known/openid-configuration` endpoint etc, which these APIs do not have.

**Comment by leastprivilege** [comment]
The "OIDC" stands for OpenID Connect. That's the focus of this library. We have not planned anything beyond that.

Feel free to fork the repo if you want to create derived work.

**Comment by hansmbakker** [comment]
@leastprivilege I understand that the OidcClient focuses on OpenID Connect.
However, I believe that the CryptoHelper class is relevant to both the `IdentityModel` package and the `IdentityModel.OidcClient` package since PKCE can be used for OAuth2 without OIDC.

Since both the `IdentityModel` package and the `IdentityModel.OidcClient` package belong to the same organization, and since the `IdentityModel.OidcClient` package already references the `IdentityModel` package, would it be possible to move the `CryptoHelper` class to the `IdentityModel` package?

**Comment by leastprivilege** [comment]
We currently have no plans to move this to IdentityModel. 

As I said before - feel free to copy the code for your own purposes.

**Comment by hansmbakker** [comment]
Can you help me understand the split between the `IdentityModel` package and the `IdentityModel.OIDCClient` package, then?

**Comment by leastprivilege** [comment]
IdentityModel tries to have minimal dependencies and provides the primitives to build higher level libraries.

**Comment by hansmbakker** [comment]
Ok that's clear, thank you.
