### ISSUE TITLE
Cannot set scope on refresn token

### ISSUE THREAD

**Issue by aguacongas** [IdentityModel/IdentityModel.OidcClient#373]
this:
```
await _oidcClient.RefreshTokenAsync(entity.RefreshToken, new Parameters(new Dictionary<string, string>
        {
            ["scope"] = scope
        })
```

throw "InvalidOperationException : Duplicate parameter: scope" and we can set a scope when refreshing a token

**Comment by leastprivilege** [comment]
I see. This requires introducing an optional scope parameter I guess.

Which STS are you using? Can you do a PR and test?

thanks!

**Comment by aguacongas** [comment]
I do not use an STS in particular, my goal is to implement [IAccessTokenProvider](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webassembly.authentication.iaccesstokenprovider?view=aspnetcore-7.0) for MAUI so it'll be easier to port a Blazor WASM app with OIDC to MAUI.  [WIP here](https://github.com/Aguafrommars/Maui.Blazor.Authentication).

I'll open a PR asap.
