### ISSUE TITLE
Missing ES384 and ES512 algorithms in the default policy

### ISSUE THREAD

**Issue by IliaOrlov** [IdentityModel/IdentityModel.OidcClient#375]
In this file
https://github.com/IdentityModel/IdentityModel.OidcClient/blob/acf47d22e4a8cd8b1ceeb4ae4dabec9e3b491cfb/src/OidcClient/Policy.cs#L70-L71

PS384 and PS512 are added twice, but ES384 and ES512 are missing

**Comment by leastprivilege** [comment]
Thanks! Could you propose a PR?

**Comment by JoC0de** [comment]
fixed in #379 see:

https://github.com/IdentityModel/IdentityModel.OidcClient/blob/0c9177cf001b38e4ba64ae252300e859df18f379/src/OidcClient/Policy.cs#L70-L71

Unfortunately there is no release containing the fix.
