### ISSUE TITLE
`Invalid access token hash` error when validating at_hash with *384 and *512 signing algorithms

### ISSUE THREAD

**Issue by IliaOrlov** [IdentityModel/IdentityModel.OidcClient#376]
I get an `Invalid access token hash`. when trying to verify an identity token containing the `at_hash` claim and one of the following signature algorithms is used: RS384, RS512 ...

I tend to think that the `CryptoHelper.ValidateHash` method calculates an incorrect hash value for algorithm if the algorithm key length is not 256.
And the reason is in these two lines:

https://github.com/IdentityModel/IdentityModel.OidcClient/blob/acf47d22e4a8cd8b1ceeb4ae4dabec9e3b491cfb/src/OidcClient/CryptoHelper.cs#L61-L62

The size variable already contains the length of the needed part of the calculated hash, there is no need in the additional calculations in this lines.

**Comment by leastprivilege** [comment]
Thanks for reporting.

Feel free to propose a fix PR - ideally with tests that exercise the various sizes.

**Comment by Jeroen-Van-Loocke** [comment]
It seems that I have the same issue (RS512).
@IliaOrlov Did you manage to fix this or found a workaround?
