### ISSUE TITLE
Upgrade - No 'XXXAzureAD' was found, upgrading from AuthenticationFlow.Hybrid

### ISSUE THREAD

**Issue by bluezebra** [IdentityModel/IdentityModel.OidcClient#385]
In upgrading from 3.1.2 I had to remove no longer compiling OidcClientOptions
```
Flow = OidcClientOptions.AuthenticationFlow.Hybrid,
ResponseMode = OidcClientOptions.AuthorizeResponseMode.FormPost,
```
But now when calling LoginAsync the StartUrl passed to my IBrowser implementation is different and fails to authenticate.

When I compare to the previous working StartUrl, it seems to be missing the query params:
```
%20id_token&nonce
&response_mode=form_post
```

**Comment by leastprivilege** [comment]
I removed hybrid flow in favour of the more recommended code flow + PKCE.
