### ISSUE TITLE
No RefreshTokenDelegatingHandler when using OidcClient.RefreshTokenAsync()

### ISSUE THREAD

**Issue by JoshJacobAtHanson** [IdentityModel/IdentityModel.OidcClient#389]
If an app securely stores the refresh token between launches and uses OidcClient.RefreshTokenAsync() on a fresh launch to get a new access token, the RefreshTokenResult doesn't contain a RefreshTokenDelegatingHandler that the LoginResult contains. Is there a reason for this or should I just create my own RefreshTokenDelegatingHandler?

**Comment by leastprivilege** [comment]
You can simply pass the stored refresh token in the handler on app restart and use that.

**Comment by JoshJacobAtHanson** [comment]
@leastprivilege Thanks for the quick reply. I'm good with that part of the process. It's the difference between OidcClient.RefreshTokenAsync() and OidcClient.LoginAsync() that I'm struggling with. Here is some stripped out code to show the differences between the two flows we have:
```
var refreshToken = // pull string from secure preferences
if (String.IsNullOrWhiteSpace(refreshToken))
{
	var result = await _oidcClient.LoginAsync();
	
	// save refresh token to secure preferences
	
	// access refresh handler from OIDC
	var handler = result.RefreshTokenHandler;
	if (handler is RefreshTokenDelegatingHandler)
	{
		// register to receive notifications of refresh
		var refreshTokenDelegatingHandler = (RefreshTokenDelegatingHandler)handler;
		refreshTokenDelegatingHandler.TokenRefreshed += RefreshTokenDelegatingHandler_TokenRefreshed;
	}

	// Configure Swagger/RestSharp to use OIDC handler which performs refresh
	RestClientOptions options = new RestClientOptions(BasePath);
	Configuration.Default.ApiClient.RestClient = new RestSharp.RestClient(new HttpClient(handler, false), options);
}
else
{
	var refreshed = await _oidcClient.RefreshTokenAsync(refreshToken);
	
	// save refresh token to secure preferences
	
	// ???
}
```
Where I have the `???` it seems I would need to manually create a `RefreshTokenDelegatingHandler` since it's only created for a `LoginResult`. Does that sound correct?

**Comment by JoshJacobAtHanson** [comment]
As a followup, I manually created the `RefreshTokenDelegatingHandler` as I mentioned and it appears to be working correctly for refreshing the access token. Here's updated code from my authentication service singleton:

```
var refreshToken = // pull string from secure preferences
if (String.IsNullOrWhiteSpace(refreshToken))
{
	// see above
}
else
{
	var refreshed = await _oidcClient.RefreshTokenAsync(refreshToken);
	
	// save refresh token to secure preferences
	
	// manually create refreshHandler
	this.refreshHandler = new RefreshTokenDelegatingHandler(_oidcClient, refreshed.AccessToken, refreshed.RefreshToken, _oidcClient.Options.RefreshTokenInnerHttpHandler);
	// register to receive notifications of refresh
	refreshHandler.TokenRefreshed += RefreshTokenDelegatingHandler_TokenRefreshed;

	// Configure Swagger/RestSharp to use OIDC handler which performs refresh
	RestClientOptions options = new RestClientOptions(BasePath);
	Configuration.Default.ApiClient.RestClient = new RestSharp.RestClient(new HttpClient(refreshHandler, false), options);
}
```

@leastprivilege I'll defer to you if the above is enough to close this issue or if you wanted to keep open for another solution.

**Comment by leastprivilege** [comment]
IIRC - you do not need to call

`var refreshed = await _oidcClient.RefreshTokenAsync(refreshToken);`

Just pass the stored refresh token into the handler, it will get refreshed automatically on usage.

**Comment by JoshJacobAtHanson** [comment]
@leastprivilege Gotcha. It wasn't apparent that the access token parameter was optional in the handler. Regardless, my team seems to like the UX of calling `RefreshTokenAsync` during app startup/login so if the refresh token is expired, the user can re-login there.

Appreciate the support and the project -- huge help in getting authentication working in a MAUI app!
