### ISSUE TITLE
Documentation: Exceptions to handle

### ISSUE THREAD

**Issue by Chris-D-Turk** [IdentityModel/IdentityModel.OidcClient#394]
Which exception types should I handle when invoking methods like `OidcClient.LoginAsync`. I can't find anything about this in the docs. This makes it very hard to handle IO related exceptions. I just had an InvalidOperationException because our OIDC-Service wasn't available. 
`System.InvalidOperationException: Error loading discovery document: Error connecting to ...`
Are there any other exception types to handle?

**Comment by leastprivilege** [comment]
I can't remember. Both source code and docs are OSS. Feel free to contribute.
