### ISSUE TITLE
Does IdentityModel.OidcClient support Private Key JWTs with certificates

### ISSUE THREAD

**Issue by eholyat** [IdentityModel/IdentityModel.OidcClient#398]
Does IdentityModel.OidcClient support the following?

I am trying to implement the Private Key JWTs with the ClientAssertion

I can't figure out how to generate the value of the ClientAssertion using the IdentityModle.OidcClient like in the example which uses IdentityModel.Client.   The request isn't available yet when the ClientAssertion is configured in the OidcClientOptions,

Am I just supposed to put the certificate in the ClientAssertion.Value and  IdentityModle.OidcClient will use it 

Similar to what is in the Duende docs
https://docs.duendesoftware.com/identityserver/v6/tokens/authentication/jwt/
using IdentityModel.Client;
static async Task<TokenResponse> RequestTokenAsync(SigningCredentials credential) {...}

**Comment by leastprivilege** [comment]
> Am I just supposed to put the certificate in the ClientAssertion.Value and IdentityModle.OidcClient will use it

No - you need to create the complete assertion and set it for OidcClient to use it.

**Comment by eholyat** [comment]
I created a good assertion and when I call oidcclient.LoginAsync() it is not sending the assertion.  Do I need to use the lower level IdentityModel Client to accomplish private key jwts with certs?

**Comment by leastprivilege** [comment]
IIRC no. Have you debugged it?

**Comment by eholyat** [comment]
So, what I found is that IdentityModel only adds the ClientAssertion in the token request for Private Key Jwt(IdentityModel.Client.ProtocolRequest.cs Prepare()).  I expected it to also be in the authorize request, and it is not added through callling LoginAsync().  
**Is there another way to do this without having to change AuthorizeClient.cs? Maybe using IdentityModel.Client.HttpClientTokenRequestExtensions???**

**The following would have to be added to IdentityModel.OidcClient.AuthorizeClient.cs
CreateAuthorizeParameters()**
...
            if (_options.RedirectUri.IsPresent())
            {
                parameters.Add(OidcConstants.AuthorizeRequest.RedirectUri, _options.RedirectUri);
            }
            /*Would need this code to add assertion if exists
           if (_options.ClientAssertion?.Value != null)
            {
                parameters.Add(OidcConstants.TokenRequest.ClientAssertion, _options.ClientAssertion.Value);
                parameters.Add(OidcConstants.TokenRequest.ClientAssertionType, _options.ClientAssertion.Type);
            }*/

**Comment by leastprivilege** [comment]
The client assertion is used on when redeeming the code. This is correct.

**Comment by brockallen** [comment]
All set on this issue -- can we close?
