### ISSUE TITLE
Is there a way to have OIDC Client not persist the login on the Duende Oauth server?

### ISSUE THREAD

**Issue by JimWilcox3** [IdentityModel/IdentityModel.OidcClient#407]
Normally, persisting the login information is a good thing on a mobile device, but I have a situation where there might be more than one user on a device.  The simple answer is to tell them to make sure they log out.  This doesn't always happen.  Is there a way to have the app login to the server and get the tokens, then log out of the server when it's done?  Maybe something I can pass to the options?

Here is my login code:

```
  _options = new OidcClientOptions
  {
      Authority = vm.Config["Settings:Authority"],
      ClientId = vm.Config["Settings:ClientId"],
      Scope = vm.Config["Settings:Scope"],
      RedirectUri = vm.Config["Settings:RedirectUri"],
      PostLogoutRedirectUri = vm.Config["Settings:RedirectUri"],
      Browser = new ChromeCustomTabsBrowser(this)
  };

  var oidcClient = new OidcClient(_options);

  var result = await oidcClient.LoginAsync();

  if (result.IsError)
  {
      vm.Logger.LogError(result.Error);
  }
  else
  {
      vm.Tokens.AccessToken = result.AccessToken;
      vm.Tokens.IdentityToken = result.IdentityToken;
      vm.Tokens.RefreshToken = result.RefreshToken;
      vm.Tokens.AccessTokenExpiration = result.AccessTokenExpiration.DateTime.ToUniversalTime();
      vm.Tokens.Error = result.Error;

      vm.Logger.LogInformation("{0} logged in!", result.User.Identity.Name);
  }

```

Thanks,
Jim

**Comment by brockallen** [comment]
For this client, you could always pass the "prompt" parameter when making the request to the authorize endpoint: https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

**Comment by JimWilcox3** [comment]
Which prompt parameter would I send?  I need the user to login with user name and password.  After the tokens are returned, I want them automatically logged off of the Duende OAuth server.

**Comment by JimWilcox3** [comment]
I am guessing I should pass "prompt login" when I make the request.  In the parameters, it doesn't seem to have an option for "prompt".  Can you tell me how to pass that parameter in the above scenario?

**Comment by JimWilcox3** [comment]
That worked.  I stumbled through passing the parameter, but it seems to always ask for the user to login.

This is what I came up with:

```
  _options = new OidcClientOptions
  {
      Authority = vm.Config["Settings:Authority"],
      ClientId = vm.Config["Settings:ClientId"],
      Scope = vm.Config["Settings:Scope"],
      RedirectUri = vm.Config["Settings:RedirectUri"],
      PostLogoutRedirectUri = vm.Config["Settings:RedirectUri"],
      Browser = new ChromeCustomTabsBrowser(this)
  };

  var oidcClient = new OidcClient(_options);

  var parm = new Parameters
  {
      { "prompt", "login" }
  };

  var result = await oidcClient.LoginAsync(new LoginRequest { FrontChannelExtraParameters = parm });

```

**Comment by brockallen** [comment]
> but it seems to always ask for the user to login.

That's exactly what that param/value combo is asking for. That was your requirement, yes?

**Comment by JimWilcox3** [comment]
Yes sir.  I didn't realize there was a way to have it always force a user to enter credentials.  This was a better fix than what I was asking for.  Thanks for the insight and solution.
