### ISSUE TITLE
OidcClient.LoginAsync fails with 'Failed to push authorization parameters' after upgrade to 6.0.0

### ISSUE THREAD

**Issue by tschbc** [IdentityModel/IdentityModel.OidcClient#434]
On .NET MAUI 8.0.x I get this 'Failed to push authorization parameters' error when invoking LoginAsync. The only change I've made in my project is upgrading IdentityModel.OidcClient from 5.2.1 -> 6.0.0.

**Comment by brockallen** [comment]
Perhaps relevant?

https://github.com/IdentityModel/IdentityModel.OidcClient/issues/428#issuecomment-2050498253

**Comment by tschbc** [comment]
Appreciate the link, I'll try using `DisablePushedAuthorization` and report back.

**Comment by tschbc** [comment]
Using `DisablePushedAuthorization` worked for me. Thanks!
